services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polosa_telegram_bot
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./photos:/usr/src/app/photos
    networks:
      - botnet

  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      # Подменяем файл конфигурации внутри контейнера на свой
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      # Примонтируем внутрь контейнера наш каталог в расположение /data
      - ./redis/data:/data
    command: "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - botnet

volumes:
  redis_data:

networks:
  botnet:
